---

- hosts: all
  tasks:

  - name: Confirm docker is installed
    sudo: True
    command: docker ps

  - name: Create ini folder on remote machine
    sudo: ubuntu
    file: dest=/home/ubuntu/ini mode=755 owner=ubuntu group=ubuntu state=directory

  - name: Copy scheduling content to remote machine
    sudo: True
    copy: src=/home/ubuntu/.scheduling dest=/home/ubuntu/ini owner=ubuntu group=ubuntu mode=0700

  - name: Install orchestra crontab
    cron: minute="*"
          name="orchestra"
          user="root"
          job="[ -e /home/ubuntu/ini/runner.sh ] && bash /home/ubuntu/ini/runner.sh 2>&1 > ~/.scheduler.txt && mv /home/ubuntu/ini/runner.sh /home/ubuntu/ini/runner.ran"
